### ISSUE TITLE
Correções e sugestões

### ISSUE THREAD

**Issue by bergolho** [rsachetto/MonoAlg3D_C#1]
Oi Sachetto,

Estou ajudando o Pedro Arroyo a começar a utilizar seu código, porém quando clonamos a última versão do repositório e começamos a testar todos os exemplos da pasta 'example_configs' nos deparamos com alguns erros. 

Abaixo vou descrever pra você os erros que aparecem quando se executa cada um destes arquivos.

**benchmark_config_example.ini:**
Error making the output directory.

Parece que existe uma pasta 'outputs' no seu repositório local que não subiu para o Github.

**cable_mesh_with_tt2006.ini:**   
OK

**cubic_mesh_with_fibrosis_example.ini:**
GPU Error!: invalid configuration argument at 
/home/berg/Github/Sachetto/MonoAlg3D_C/src/models_library/ten_tusscher_3_RS_GPU.cu 22

Acho que o erro está quando se configura a 'fibrose' no modelo do TenTusscher3.

**cuboid_ohara.ini**
Error making the output directory.

Mesmo erro que ocorre no "benchmark_config_example.ini"

**cuboid_tentusscher4.ini**
A simulação rodou perfeitamente, porém o Paraview não conseguiu carregar os arquivos.
Olhei o nome dos arquivos de saída e verifiquei que tem aspas duplas adicionais.
O nome dos arquivos está saindo assim: "V_t_"_it_0_ms.vtu
Acho que o erro está na função "save_as_vtk" na parte de colocar o "file_prefix".

**fhn_random_conductivities_2D.ini**
OK

**human_big_scar_wedge_with_fibrosis.ini**
Está faltando a malha "human_800_scars_tagged.alg".

**human_mesh_no_fibrosis_config_example.ini**
Está faltando a malha "human_800.alg" e o arquivo "stim.pts".

**human_mesh_with_fibrosis_config_example.ini**
Está faltando a malha "human_800_scars_tagged.alg" e o arquivo "stim.pts".

**human_mesh_with_two_scars_and_fibrosis_from_file.ini**
Está faltando a malha "human_800_scars_tagged.alg", o arquivo "stim.pts" e os arquivos de configuração da cicatriz "big_scar.pts", "small_scar_2.pts".

**human_small_scar_wedge_with_fibrosis.ini**
Está faltando a malha "human_800_scars_tagged.alg".

**mouse_mesh_config_example.ini**
Está faltando a malha "mouse.alg".

**mouse_mesh_spiral_config_example.ini**
Está faltando a malha "mouse.alg".

**plain_mesh_no_fibrosis_example.ini**
'initialize_grid_with_square_mesh' function not found in the provided domain library.

**plain_mesh_with_fibrosis_and_border_zone_inside_circle_example.ini**
Invalid name use_preconditioner in section main on the config file!

**plain_mesh_with_fibrosis.ini**
Mesmo erro do 'cubic_mesh_with_fibrosis_example.ini'.

**rabbit_mesh_config_example.ini**
Consome muita memória, vou testar no cluster.

Além disso, notei que novas funcionalidades foram adicionadas, como por exemplo a inclusão de Checkpoints para salvar o estado das simulações. Acho que seria interessante adicionar alguns exemplos que demonstram esta funcionalidade. 

Outra coisa, acho bom dar uma melhorada no "README.md" colocando os pré-requisitos pra dar build no projeto. Por exemplo, para configurar esta última versão do repositório na minha máquina aqui tive que instalar o GCC 5.3.0 e usar ele no caminho padrão na hora de chamar o CMake. Senão fizesse isso dava erro na hora de compilar os arquivos ".cu". Fora isso tive que instalar dois pacotes do GTK para funcionar no Fedora 28: "gtk3-devel" e "gtksourceview3-devel".

[]'s
Lucas

**Comment by rsachetto** [comment]
Obrigado pelas sugestões. O último commit corrigi praticamente todos os bugs que vc relatou.
