### ISSUE TITLE
Batch config does not execute

### ISSUE THREAD

**Issue by PeihengLu** [rsachetto/MonoAlg3D_C#66]
Hi!

I'm trying to execute the batch_cable_config.ini provided in the example configurations using the command:

`./bin/MonoAlg3D -c example_configs/batch_cable_config.ini`

This resulted in the following errors:

```
Invalid name initial_config in section batch on the config file!
Invalid name output_folder in section batch on the config file!
Invalid name num_simulations_per_parameter_change in section batch on the config file!
Invalid name extra_data|atpi in section modify on the config file!
Invalid name extra_data|Ko in section modify on the config file!
Invalid name extra_data|GNa_multiplicator in section modify on the config file!
Invalid name extra_data|GCaL_multiplicator in section modify on the config file!
```

**Comment by PeihengLu** [comment]
Hi Rafael!

Thank you so much for your rapid reply! I do not seem to have ./bin/MonoAlg3D_batch executable after compilation. Is there a specific compilation command needed when executing build.sh?

I currently only MonoAlg3D.

**Comment by rsachetto** [comment]
@PeihengLu, how did you compile the simulator? You need to have a MPI installed in the computer to compile the batch simulator.

**Comment by PeihengLu** [comment]
@rsachetto I just execute the ./build.sh script with no additional arguments. I'll install MPI first and see what happens!

**Comment by rsachetto** [comment]
Ok, let me know if the MPI version compiles after the installation. Sometimes we have to manually change some parameters in the build system.

**Comment by PeihengLu** [comment]
Hi @rsachetto! I now have `MonoAlg3D  MonoAlg3D_clip_mesh  MonoAlg3D_converter  MonoAlg3D_expand_scar  MonoAlg3D_fiber_converter  MonoAlg3D_postprocessor  MonoAlg3D_visualizer` built, but still no `MonoAlg3D_batch`

**Comment by PeihengLu** [comment]
Thank you so much for your help! It is working now.

For posterity, in my case, the openmpi installation was found in:`/usr/lib/x86_64-linux-gnu/openmpi/lib`, and the `mpi.h` file was found in `/usr/lib/x86_64-linux-gnu/openmpi/include`
