### ISSUE TITLE
Error on new "matrix_assembly" function

### ISSUE THREAD

**Issue by bergolho** [rsachetto/MonoAlg3D_C#8]
Hello Sachetto,

I just got this new version of the solver in order to test new features and when I was compiling on my Fedora machine I found an error in the "matrix_assembly.c" file on line 129.

`n = get_cell_neighbour_as_void(cell, cell->y_top->x_right, &cell_type);`
			`if(n) num_not_null++;`
			`arrput(*neighbours, (struct basic_cell_data *)n);`

The following error message:
`/home/berg/MonoAlg3D_C/src/matrix_assembly_library/matrix_assembly.c:129:52: error: request for member ‘x_right’ in something not a structure or union`

**Comment by rsachetto** [comment]
Thanks. Corrected by the last commit.
